version: "3.7"
services:
  server:
    container_name: thenewsreader
    image: $PROJECT_NAME:$IMAGE_TAG
    ports:
      - "80:80"
    networks:
      - thenewsreader_net
    restart: unless-stopped

networks:
  thenewsreader_net: ~
