- name: Remove build and local files
  file:
    dest: '/tmp/{{ item }}'
    state: absent
  delegate_to: 127.0.0.1
  with_items:
    - '{{ project_name }}'
    - '{{ project_name }}.tgz'
  tags:
    - clean_local
  run_once: yes
