- name: Upload current storybook to production
  copy:
    src: "/tmp/{{ project_name }}.tgz"
    dest: "{{ remote_releases_folder }}"
    remote_src: no

- name: Create release directory
  file:
    dest: "{{ remote_releases_folder }}/{{ datetime }}"
    state: directory

- name: Unarchive release
  unarchive:
    src: "{{ remote_releases_folder }}/{{ project_name }}.tgz"
    dest: "{{ remote_releases_folder }}/{{ datetime }}"
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: Remove compressed file
  file:
    state: absent
    dest: "{{ remote_releases_folder }}/{{ project_name }}.tgz"

- name: Change release
  file:
    src: "{{ remote_releases_folder }}/{{ datetime }}"
    path: "{{ remote_project_folder }}/current"
    state: link
    force: yes

- name: Remove old releases
  deploy_helper:
    path: "{{ remote_project_folder }}"
    release: "{{ remote_releases_folder }}/{{ datetime }}"
    releases_path: "{{ remote_releases_folder }}"
    state: clean
    keep_releases: "{{ amount_of_releases }}"
